---
language: python
services: redis-server
python:
 - 2.6
 - 2.7
 - 3.4
 - 3.5
 - pypy
install:
 - pip install tox==2.3.1 tox-travis==0.4
 - pip install coveralls codeclimate-test-reporter codacy-coverage codecov>=1.4.0
script: tox
after_script:
 - tox -e coverage
 - tox -e static_analysis
 - codecov -e TOXENV
 - coveralls
 - codeclimate-test-reporter
 - python-codacy-coverage -r coverage.xml
